sudo: false
language: python

stage: test

env:
  global:
    # $PYPIPASS
    secure: "U30TabwR6nCqHJeuO9xW9YhGa8VZLzS4u5arD+br/cDx3aU/ioPmg3Tguc9vmwujZDdDFgEP3imN2SS6ljAYk5Rff0e8wll76at3Do2hvPXXKfpKmYfGbhvAdFIKiAD+PDROBrARfWm4kRhLc+4nB++jumwP9D1QrU0Un/bBDoWYoHCL7fRI+HJr5Pq3wGEje+mzh9U4KQhh70ddfy1ReOKHYxXaLduLog+taOFzoh1+fez+hKknsvawVLZ3wo2AvXdKXw8XezLfWNkDuaaJRPH5tGxH62bYWJVIUcXm0COEETpFMRdRmyOuHAZ2Cr+kSgdfB3zmw6BshaxtvYwBok6HsttLViALtEZhvj2myOwnP6pMAsG/5VzzpKbgM1dHdTdygEg/FxhDWC3+ng1jjhcGxCqeHef6SNNtJf+GehFYhO0fqT6NeD0HanVzKWv48EgcMK8cYsh4SwN6j2Gp1EjEql9TSOMlWiRasSX90kH0NuAyU+FMNcAYpxitoY3aVYNixRayUVIglXC08qaqSIPlcLcq20HpNB2qymp7L/7hEp6GjH/CuVm8wxnxIu5L4LORtWD7VZdoMHZpTYIftqIlA0+QcYX0DJueyafhnt8nH7AwIUqIuDOxegildq1+n3lK2xO23TdGH8G6UthroB9lVdcRGhBfFo710gUEJ80="

matrix:
  fast_finish: true
  include:

    - python: '2.7'
      env: FOO=1

    - python: '2.7'
      env: FOO=2

    - stage: deploy
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      install:
        - if [[ -z $TRAVIS_TAG ]]; then exit 0; fi # exit early if it's not a tag
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/travis/build-wheels.sh
        - pip install twine
        - twine upload -u antocuni.wheelbuilder -p $PYPIPASS dist/* wheelhouse/*

cache:
  pip: true
  directories:
  - $HOME/capnp


install:
  - pip install -U pip # so that we can use wheels
  - pip install cython>=0.25

script:
  - echo foo $FOO
  - echo deploy $DEPLOY
  - python setup.py build_ext --inplace
  - py.test
