apiVersion: v1
kind: Service
metadata:
  name: {{ project_name }}
  labels:
    app.kubernetes.io/name: {{ project_name }}-app
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: {{ project_name }}
spec:
  clusterIP: None
  ports:
    - port: 8000
      name: {{ project_name }}-app
  selector:
    app.kubernetes.io/name: {{ project_name }}-app
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: {{ project_name }}
