{% if db %}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ project_name }}-app
spec:
  template:
    spec:
      containers:
      - name: {{ project_name }}-app
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ project_name }}-db
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ project_name }}-db
                key: POSTGRES_PASSWORD
{% endif %}
