[tool.poetry]
name = "django-snippet-image"
version = "0.1.2"
description = "Django field for create snippet image for sharing in social networks."
license = "MIT"
authors = ["acrius <acrius@mail.ru>"]

readme = 'README.rst'

repository = "https://github.com/acrius/django-snippet-image"
homepage = "https://github.com/acrius/django-snippet-image"

keywords = ['django', 'sharing', 'images', 'social', 'networks', 'snippets']

[tool.poetry.dependencies]
python = "^3.5"
django = "^1.11 || ^2.0"
snippet-image = "^0.1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
